# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ed9c91ff6aeb210ce5c35ceecbe5468c30f8ffc212584d6c27cdaa28e20a4806edd8012fd582db6a879ca75d2b186fa5786651f93abcc7187caae1a6ef88e01

test:
  secret_key_base: 622588ff8912406b7dc2e075df83e22e42de17f44b8f4b734f422d25fd225c8bed7d69596b505be5434c4f23096437e65e6196de9f5cf498beab32c32b57d681

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
